language: ruby
rvm:
- 2.2.5
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
branches:
  only:
  - master
install:
- bundle install
script:
- wget -O ./_data/news.csv $(bundle exec yaml get news-feed -F=_config.yml)
- wget -O ./_data/events.csv $(bundle exec yaml get events-feed -F=_config.yml)
- wget -O ./_data/profiles.csv $(bundle exec yaml get faculty-feed -F=_config.yml)
- bundle exec jekyll build
- bundle exec htmlproofer ./_site --check-html --check-favicon --allow-hash-href
  --external_only --only-4xx --http-status-ignore 429
after_success: s3_website push
notifications:
  slack:
    rooms:
      - secure: FnseyHIV5QlKsko7Bq4IvXKHpEyvLWlbAz/bpShRTp/UEtZZxNRZNkw5a8OQSlzUqWKNBuQ4PWc/RfAP6EnsJ4oNdw+hFWAFBkp8IkHIMyYjzyyeEZ0agMP5byy7zaRI1MagzvvGtK63TpD/KmFrpMtYu7cLjIu8PdxGxxYoI4o1dzYi5exhv/nv6cZ5pz1iUZIQrL02GPDocBOFa1ahnzTyEGhQXBuG+op0xrWFPFoQ/vAqQBpmAwkMhiEF0vxmvIaS9DyvOajBqaxaYuC5TVRPvD1wIQxHzTEfC2KrHBUnGKjROMkOoFQXDw3Cno+kIoi88D46GmxmyQo701hF6/gQCC5xALO5wCGsfTHBxTWjuT8vr2eBEmdw1GQpFtZ6PTSgeMw0Pi1zGzW6tS+sHuGmGA/QaJvsQSTaDkWZPgSyk+Of1mJ0GxS8lw5Du0S2tr+A8vz1BLRmlTOvFkqTPIval9SJv+xwEs45zldwLKPd/Kludbq6/UnIuS6IoQR5bhAjSmLQhl5BSpKPRtTXSVX+FYTfK5EIYHP5M5plsko0wdt1AnZVpHufUz8Y+0WShgEVDBXfzQmckO+vroCEMkJvOzPXSWg373EIYK7AgO1zXB3jA/1tGOXea5PeMh7hc10jJttH9xn1XEha7AzEzaPo/ZhAOFlEuV26Gf30n6Y=
    on_success: always
